spring.application.name=Analiso
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.uylzwlpkqggeajbdujyo.supabase.co:5432/postgres?sslmode=require&characterEncoding=UTF-8&useUnicode=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bEbkr%E/Et#9jC_}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
app.db.schema=${APP_DB_SCHEMA:analiso}
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
pipeline.trigger.url=${PIPELINE_TRIGGER_URL:http://localhost:8090}
app.auth.google.client-id=${APP_AUTH_GOOGLE_CLIENT_ID:443722990095-fssh39e39fr204tuphhlbnfu2rde3t7m.apps.googleusercontent.com}
app.auth.jwt.secret=${APP_AUTH_JWT_SECRET:change-this-secret-change-this-secret-change-this-secret}
app.auth.jwt.expiration-minutes=${APP_AUTH_JWT_EXPIRATION_MINUTES:1440}
spring.flyway.enabled=true
spring.flyway.schemas=${APP_DB_SCHEMA:analiso}
spring.flyway.default-schema=${APP_DB_SCHEMA:analiso}
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0


